-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 20:36:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema businessapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema businessapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `businessapp` DEFAULT CHARACTER SET utf8 ;
USE `businessapp` ;

-- -----------------------------------------------------
-- Table `businessapp`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`player` (
  `playerId` INT NOT NULL AUTO_INCREMENT,
  `playerPrename` VARCHAR(45) NULL,
  `playerSurname` VARCHAR(45) NULL,
  `playerEmail` VARCHAR(45) NULL,
  `playerImg` VARCHAR(45) NULL,
  `playerSpecial` TINYINT(1) NULL COMMENT '0 = regular\n1 = Speciall Player - players on ranking List\n2 = Ghost  Player - ghost time for points (default)',
  PRIMARY KEY (`playerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`dribbleTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`dribbleTraining` (
  `dribbleTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `dribble1` TIME NULL,
  `dribble2` TIME NULL,
  `dribble3` TIME NULL,
  `dribblePoints` INT NULL,
  PRIMARY KEY (`dribbleTrainingId`),
  INDEX `fk_dribbleTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_dribbleTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`speedTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`speedTraining` (
  `speedTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `speed1` TIME NULL,
  `speed2` TIME NULL,
  `speed3` TIME NULL,
  `speedPoints` INT NULL,
  PRIMARY KEY (`speedTrainingId`),
  INDEX `fk_speedTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_speedTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`shootTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`shootTraining` (
  `shootTrainingId` INT NOT NULL,
  `fk_playerId` INT NOT NULL,
  `shoot1` TIME NULL,
  `shoot2` TIME NULL,
  `shoot3` TIME NULL,
  `shootPoints` INT NULL,
  PRIMARY KEY (`shootTrainingId`),
  INDEX `fk_shootTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_shootTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`moralTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`moralTraining` (
  `moralTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `moral1` TIME NULL,
  `moral2` TIME NULL,
  `moral3` TIME NULL,
  `moralPoints` INT NULL,
  PRIMARY KEY (`moralTrainingId`),
  INDEX `fk_moralTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_moralTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`leadershipTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`leadershipTraining` (
  `leadershipTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `leadership1` TIME NULL,
  `leadership2` TIME NULL,
  `leadership3` TIME NULL,
  `leadershipPoints` INT NULL,
  PRIMARY KEY (`leadershipTrainingId`),
  INDEX `fk_leadershipTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_leadershipTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`staminaTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`staminaTraining` (
  `staminaTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `stamina1` TIME NULL,
  `stamina2` TIME NULL,
  `stamina3` TIME NULL,
  `staminaPoints` INT NULL,
  PRIMARY KEY (`staminaTrainingId`),
  INDEX `fk_staminaTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_staminaTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`passTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`passTraining` (
  `passTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `pass1` TIME NULL,
  `pass2` TIME NULL,
  `pass3` TIME NULL,
  `passPoints` INT NULL,
  PRIMARY KEY (`passTrainingId`),
  INDEX `fk_passTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_passTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`techniqueTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`techniqueTraining` (
  `techniqueTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `technique1` TIME NULL,
  `technique2` TIME NULL,
  `technique3` TIME NULL,
  `techniquePoints` INT NULL,
  PRIMARY KEY (`techniqueTrainingId`),
  INDEX `fk_techniqueTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_techniqueTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `businessapp`.`fatiqueTraining`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessapp`.`fatiqueTraining` (
  `fatiqueTrainingId` INT NOT NULL AUTO_INCREMENT,
  `fk_playerId` INT NOT NULL,
  `fatique1` TIME NULL,
  `fatique2` TIME NULL,
  `fatique3` TIME NULL,
  `fatiquePoints` INT NULL,
  PRIMARY KEY (`fatiqueTrainingId`),
  INDEX `fk_fatiqueTraining_player1_idx` (`fk_playerId` ASC),
  CONSTRAINT `fk_fatiqueTraining_player1`
    FOREIGN KEY (`fk_playerId`)
    REFERENCES `businessapp`.`player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
